# Generated by Django 4.2.7 on 2023-11-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Livros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_livro", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("n_paginas", models.IntegerField()),
            ],
        ),
    ]
